env: "local"
dsn: "postgresql://postgres:postgres@localhost:5432/go-project-db?sslmode=disable"
jwt_key: "spider-man-Sdu-Otrivin"
http_server: 
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "mypass"